import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const MANAGED_START = "# >>> crewcoder managed pre-commit >>>";
const MANAGED_END = "# <<< crewcoder managed pre-commit <<<";

export type PreCommitInstallResult = {
  repoRoot: string;
  hookPath: string;
  status: "installed" | "updated" | "unchanged" | "replaced";
  backupPath?: string;
};

export function installPreCommitHook(options: {
  cwd: string;
  command?: string;
  budget?: string;
  force?: boolean;
}): PreCommitInstallResult {
  const repoRoot = git(options.cwd, ["rev-parse", "--show-toplevel"]);
  if (!repoRoot) throw new Error("crewcoder hook install must run inside a Git repository.");
  const gitDir = git(repoRoot, ["rev-parse", "--absolute-git-dir"]);
  if (!gitDir) throw new Error("Could not resolve this repository's Git directory.");
  const gitCommonDir = git(repoRoot, ["rev-parse", "--path-format=absolute", "--git-common-dir"]);
  const gitHookPath = git(repoRoot, ["rev-parse", "--git-path", "hooks/pre-commit"]);
  if (!gitHookPath) throw new Error("Could not resolve Git's pre-commit hook path.");
  const hookPath = path.isAbsolute(gitHookPath) ? gitHookPath : path.resolve(repoRoot, gitHookPath);
  if (!isWithin(repoRoot, hookPath) && !isWithin(gitDir, hookPath) && (!gitCommonDir || !isWithin(gitCommonDir, hookPath))) {
    throw new Error([
      `Git's effective hooks path resolves outside this repository: ${hookPath}`,
      "CrewCoder refuses to modify a shared/global hook.",
      "Configure a repository-local core.hooksPath, then re-run `crewcoder hook install`."
    ].join("\n"));
  }
  return installPreCommitHookAtPath(hookPath, {
    repoRoot,
    command: options.command,
    budget: options.budget,
    force: options.force
  });
}

export function installPreCommitHookAtPath(hookPath: string, options: {
  repoRoot: string;
  command?: string;
  budget?: string;
  force?: boolean;
}): PreCommitInstallResult {
  const command = options.command?.trim() || "crewcoder";
  if (command.includes("\n") || command.includes("\0")) throw new Error("Hook command must be a single executable path.");
  const budget = options.budget?.trim();
  if (budget && (budget.includes("\n") || budget.includes("\0"))) throw new Error("Hook budget must be a single value.");

  const renderedHook = renderPreCommitHook({ command, budget });
  const managedBlock = renderManagedBlock({ command, budget });
  let content = renderedHook;
  let status: PreCommitInstallResult["status"] = "installed";
  let backupPath: string | undefined;

  if (fs.existsSync(hookPath)) {
    const existing = fs.readFileSync(hookPath, "utf8");
    if (existing === renderedHook) {
      fs.chmodSync(hookPath, 0o755);
      return { repoRoot: options.repoRoot, hookPath, status: "unchanged" };
    }
    if (isManagedHook(existing)) {
      content = replaceManagedBlock(existing, managedBlock);
      if (content === existing) {
        fs.chmodSync(hookPath, 0o755);
        return { repoRoot: options.repoRoot, hookPath, status: "unchanged" };
      }
      status = "updated";
    } else {
      if (!options.force) {
        throw new Error(`A non-CrewCoder pre-commit hook already exists at ${hookPath}. Re-run with --force to back it up and install CrewCoder's hook.`);
      }
      backupPath = nextBackupPath(hookPath);
      fs.renameSync(hookPath, backupPath);
      status = "replaced";
    }
  }

  fs.mkdirSync(path.dirname(hookPath), { recursive: true });
  fs.writeFileSync(hookPath, content, { encoding: "utf8", mode: 0o755 });
  fs.chmodSync(hookPath, 0o755);
  return {
    repoRoot: options.repoRoot,
    hookPath,
    status,
    ...(backupPath ? { backupPath } : {})
  };
}

export function renderPreCommitHook(options: { command: string; budget?: string }): string {
  return ["#!/bin/sh", renderManagedBlock(options), ""].join("\n");
}

function renderManagedBlock(options: { command: string; budget?: string }): string {
  const budgetArgs = options.budget ? ` --budget ${shellQuote(options.budget)}` : "";
  return [
    MANAGED_START,
    "# Generated by `crewcoder hook install`. Re-running the command updates this managed hook.",
    "",
    'if [ "${CREWCODER_PRE_COMMIT_SKIP:-0}" = "1" ]; then',
    "  exit 0",
    "fi",
    "",
    "if git diff --cached --quiet --exit-code; then",
    "  exit 0",
    "fi",
    "",
    `CREWCODER_COMMAND=${shellQuote(options.command)}`,
    'if ! command -v "$CREWCODER_COMMAND" >/dev/null 2>&1; then',
    '  echo "CrewCoder pre-commit hook: $CREWCODER_COMMAND is not available." >&2',
    "  exit 1",
    "fi",
    "",
    "prompt='Review the staged changes using git diff --cached. Do not modify files or the index. Check correctness, security, regressions, and missing tests. Run the repository verification gate and report actionable findings clearly. End the final response with exactly CREWCODER_REVIEW_RESULT: PASS when there are no blocking findings, or CREWCODER_REVIEW_RESULT: FAIL when the commit should be blocked.'",
    `summary=$("$CREWCODER_COMMAND" run --ci --approval always${budgetArgs} "$prompt")`,
    "status=$?",
    "printf '%s\\n' \"$summary\"",
    'if [ "$status" -eq 0 ]; then',
    '  case "$summary" in',
    '    *"CREWCODER_REVIEW_RESULT: FAIL"*)',
    '      echo "CrewCoder reported blocking review findings." >&2',
    "      status=1",
    "      ;;",
    '    *"CREWCODER_REVIEW_RESULT: PASS"*)',
    "      ;;",
    "    *)",
    '      echo "CrewCoder review did not return the required PASS/FAIL marker. Commit blocked." >&2',
    "      status=1",
    "      ;;",
    "  esac",
    "fi",
    'if [ "$status" -ne 0 ]; then',
    '  echo "CrewCoder pre-commit review failed (exit $status). Commit blocked." >&2',
    "fi",
    'exit "$status"',
    MANAGED_END
  ].join("\n");
}

function isManagedHook(content: string): boolean {
  const start = content.indexOf(MANAGED_START);
  return start >= 0 && content.indexOf(MANAGED_END, start + MANAGED_START.length) >= 0;
}

function replaceManagedBlock(content: string, managedBlock: string): string {
  const start = content.indexOf(MANAGED_START);
  const end = content.indexOf(MANAGED_END, start);
  if (start < 0 || end < 0) return content;
  return `${content.slice(0, start)}${managedBlock}${content.slice(end + MANAGED_END.length)}`;
}

function nextBackupPath(hookPath: string): string {
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  let candidate = `${hookPath}.backup-${stamp}`;
  let suffix = 1;
  while (fs.existsSync(candidate)) {
    candidate = `${hookPath}.backup-${stamp}-${suffix}`;
    suffix += 1;
  }
  return candidate;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\"'\"'")}'`;
}

function isWithin(parent: string, target: string): boolean {
  const relative = path.relative(path.resolve(parent), path.resolve(target));
  return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
}

function git(cwd: string, args: string[]): string {
  try {
    return execFileSync("git", args, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return "";
  }
}
